type: object
required:
  - type
properties:
  type:
    type: string
    description: Graphics type
    enum:
      - vnc
      - spice
      - egl-headless
      - none
    example: vnc
  port:
    type: integer
    description: Port number (-1 for auto)
    default: -1
  autoport:
    type: boolean
    description: Auto-assign port
    default: true
  listen:
    type: string
    description: Listen address
    default: 127.0.0.1
    example: 0.0.0.0
  password:
    type: string
    description: Console password
    format: password
