---
- name: Install Libvirt/KVM packages (Debian)
  apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virtinst
      - osinfo-db-tools
      - libosinfo-bin
    state: present
  when: ansible_os_family == "Debian"

- name: Install Libvirt/KVM packages (RedHat)
  yum:
    name:
      - qemu-kvm
      - libvirt
      - libvirt-client
      - virt-install
      - osinfo-db-tools
      - libosinfo
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure Libvirt service is started and enabled
  systemd:
    name: libvirtd
    state: started
    enabled: yes
    daemon_reload: yes
